# Generated by Django 3.1 on 2020-08-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('pk_x', models.AutoField(db_column='pk', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('web_site', models.URLField()),
                ('token', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pk_x', models.AutoField(db_column='pk', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('special_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('count', models.IntegerField()),
                ('image', models.URLField()),
                ('seller', models.CharField(max_length=22)),
            ],
        ),
    ]
