# Generated by Django 3.1 on 2020-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_usermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='datetime_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
