# Generated by Django 3.1 on 2020-08-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0005_auto_20200822_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
