# Generated by Django 3.1 on 2020-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0008_auto_20200823_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_token',
            field=models.CharField(max_length=32),
        ),
    ]
